src/johan_production/objects/Fridge_Reading_Daily_History__c.object
<CustomObject>
    <fields>
        <fullName>DeviceId__c</fullName>
        <label>DeviceId</label>
        <length>16</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Door__c</fullName>
        <label>Door</label>
        <length>9</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Humidity__c</fullName>
        <label>Humidity</label>
        <precision>6</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Temperature__c</fullName>
        <label>Temperature</label>
        <precision>6</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ts__c</fullName>
        <label>ts</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Fridge Reading Daily History</label>
    <nameField>
        <displayFormat>FR-{000000}</displayFormat>
        <label>Fridge Reading Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fridge Readings Daily History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/johan_production/objects/Fridge_Reading_History__b.object
<CustomObject>
    <fields>
        <fullName>DeviceId__c</fullName>
        <label>DeviceId</label>
        <length>16</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Door__c</fullName>
        <label>Door</label>
        <length>9</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Humidity__c</fullName>
        <label>Humidity</label>
        <precision>10</precision>
        <required>true</required>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Temperature__c</fullName>
        <label>Temperature</label>
        <precision>10</precision>
        <required>true</required>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ts__c</fullName>
        <label>ts</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Fridge Reading History</label>
    <pluralLabel>Fridge Readings History</pluralLabel>
</CustomObject>

src/johan_production/classes/ArchiveTemperatureReadings.cls
/**
 * Created by Johan Karlsteen on 2017-10-08.
 */

global class ArchiveTemperatureReadings implements Schedulable {
    global void execute(SchedulableContext ctx) {
        doWork();
    }

    public void doWork() {
        Datetime lastReading = [SELECT DeviceId__c, Temperature__c, ts__c FROM Fridge_Reading_History__b LIMIT 1].ts__c;
        for(List<Fridge_Reading_Daily_History__c> toArchive : [SELECT Id,ts__c,DeviceId__c,Door__c,Temperature__c,Humidity__c
                                                                FROM Fridge_Reading_Daily_History__c
                                                                WHERE ts__c >: lastReading]) {
            List<Fridge_Reading_History__b> updates = new List<Fridge_Reading_History__b>();
            for (Fridge_Reading_Daily_History__c event : toArchive) {
                Fridge_Reading_History__b frh = new Fridge_Reading_History__b();
                frh.DeviceId__c = event.DeviceId__c;
                frh.Door__c = event.Door__c;
                frh.Humidity__c = event.Humidity__c;
                frh.Temperature__c = event.Temperature__c;
                frh.ts__c = event.ts__c;
                updates.add(frh);
            }
            Database.insertImmediate(updates);
        }
    }
}