src/johan_production/objects/Fridge_Reading_Daily_History__c.object
<CustomObject>
    <fields>
        <fullName>ts__c</fullName>
        <label>ts</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Fridge Reading Daily History</label>
    <nameField>
        <displayFormat>FR-{000000}</displayFormat>
        <label>Fridge Reading Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fridge Readings Daily History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/johan_production/classes/PurgeDailyFridgeReadings.cls
/**
 * Created by Johan Karlsteen on 2017-10-08.
 */

public class PurgeDailyFridgeReadings implements Queueable {

        private Datetime lastReading;

        public PurgeDailyFridgeReadings(Datetime lastReading) {
            this.lastReading = lastReading;
        }

        public void execute(QueueableContext context) {
            for(List<Fridge_Reading_Daily_History__c> readings :
                [SELECT Id FROM Fridge_Reading_Daily_History__c WHERE ts__c >: lastReading]) {
                delete readings;
            }
        }

    }