src/johan_production/objects/Fridge_Reading_History__b.object
<CustomObject>
    <fields>
        <fullName>DeviceId__c</fullName>
        <label>DeviceId</label>
        <length>16</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Door__c</fullName>
        <label>Door</label>
        <length>9</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Humidity__c</fullName>
        <label>Humidity</label>
        <precision>10</precision>
        <required>true</required>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Temperature__c</fullName>
        <label>Temperature</label>
        <precision>10</precision>
        <required>true</required>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ts__c</fullName>
        <label>ts</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Fridge Reading History</label>
    <pluralLabel>Fridge Readings History</pluralLabel>
</CustomObject>

src/johan_production/classes/FridgeReadingHistoryController.cls
/**
 * Created by Johan Karlsteen on 2017-10-08.
 */

public with sharing class FridgeReadingHistoryController {

    public class FridgeReading {
        public String deviceId {get;set;}
        public List<Datetime> ts {get;set;}
        public List<Datetime> doorTs {get;set;}
        public List<Integer> door {get;set;}
        public List<Double> temperature {get;set;}
        public List<Double> humidity {get;set;}
        public FridgeReading(String deviceId) {
            this.deviceId = deviceId;
            this.ts = new List<Datetime>();
            this.doorTs = new List<Datetime>();
            this.door = new List<Integer>();
            this.temperature = new List<Double>();
            this.humidity = new List<Double>();
        }
        public void addReading(Fridge_Reading_History__b  frh) {
            if(ts.size() < 200) {
                ts.add(frh.ts__c);
                temperature.add(frh.Temperature__c);
                humidity.add(frh.Humidity__c);
            }
            if(door.size()<200) {
                Integer doorStatus = frh.Door__c == 'open' ? 1 : 0;
                if(door.size() == 0 || doorStatus != door.get(door.size()-1)) {
                    door.add(doorStatus);
                    doorTs.add(frh.ts__c);                
                }
            }
        }
    }

    @AuraEnabled
    public static String getFridgeReadings(String deviceId) {
        FridgeReading fr = new FridgeReading(deviceId);
        List<Fridge_Reading_History__b> frhs = [SELECT DeviceId__c, Temperature__c, Humidity__c, Door__c, ts__c
                                                FROM Fridge_Reading_History__b WHERE DeviceId__c =: deviceId LIMIT 300];
        Integer skip = 0;
        for(Integer i=frhs.size()-1;i>=0;i--) {
             Fridge_Reading_History__b frh = frhs[i];
            if(Math.mod(skip,1) == 0) {
                fr.addReading(frh);
            }
            skip++;
        }
        return JSON.serialize(fr);
    }
}